version: '3'
services:
  nifi-arya:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nifi-arya

    ports:
      - "8443:8443"
    volumes:
      - ./data:/usr/src/app/data
      - ./logs:/usr/src/app/logs
