version: '3'
services:
  nifi-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nifi-container
    restart: always
    ports:
      - "8443:8443"
    volumes:
      - ./data:/usr/src/app/data
      - ./logs:/usr/src/app/logs
