version: '3'
services:
  my-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: nifi
    container_name: nifi
    ports:
      - "8443:8443"
    command: bash launcher_nifi.sh

   
